name: Update Issue with GraphQL ID

on:
  issues:
    types: [opened]

jobs:
  update_issue:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update issue with GraphQL ID
      run: |
        # Her kan du legge til skriptet som sender en GraphQL-forespørsel for å hente og oppdatere issue-informasjon.
        # Du vil sannsynligvis trenge å bruke et eksternt verktøy eller script for å gjøre dette.