name: Update Issue with GraphQL ID


# This action is triggered when an issue is opened or edited
on:
  issues:
    types: [opened, edited]

jobs:
  update_issue:
    runs-on: ubuntu-latest
    steps:
    # Check out the repository to access its content
    - name: Checkout repository
      uses: actions/checkout@v2

    # Update the issue with its GraphQL ID
    - name: Update issue with GraphQL ID
      env:
        GH_TOKEN: ${{ secrets.MY_PAT }} # Use the personal access token
      run: |
        # Get the body of the newly created issue
        BODY=$(gh issue view ${{ github.event.issue.number }} --json body -q ".body")

        # Fetch the GraphQL ID of the issue using curl
        GRAPHQL_ID=$(curl -s -H "Authorization: Bearer $GH_TOKEN" -X POST -d '{
          "query": "query ($owner: String!, $repo: String!, $number: Int!) {
            repository(owner: $owner, name: $repo) {
              issue(number: $number) {
                id
              }
            }
          }",
          "variables": {
            "owner": "'${{ github.repository_owner }}'",
            "repo": "'${{ github.event.repository.name }}'",
            "number": '${{ github.event.issue.number }}'
          }
        }' https://api.github.com/graphql | jq -r '.data.repository.issue.id')

        # Append the GraphQL ID to the issue body
        UPDATED_BODY="$BODY\n\n**GraphQL ID**: $GRAPHQL_ID"

        # Update the issue with the new body
        gh issue update ${{ github.event.issue.number }} --body "$UPDATED_BODY" --token $GH_TOKEN