name: Update Issue with GraphQL ID

on:
  issues:
    types: [opened, edited]

jobs:
  update_issue:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update issue with GraphQL ID
      run: |
        # Get the body of the newly created issue
        ISSUE_BODY=$(gh issue view ${{ github.event.issue.number }} --json body -R ${{ github.repository }} | jq -r .body)
        
        # Check if the GraphQL ID placeholder exists in the issue body
        if [[ $ISSUE_BODY == *"[TO BE FILLED]"* ]]; then
          # Replace the placeholder with the actual GraphQL ID
          UPDATED_BODY=$(echo "$ISSUE_BODY" | sed "s/\[TO BE FILLED\]/${{ github.event.issue.node_id }}/g")
          
          # Update the issue with the new body
          echo "$UPDATED_BODY" > updated_body.txt
          gh issue edit ${{ github.event.issue.number }} --body "$(cat updated_body.txt)" -R ${{ github.repository }}
        fi
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}